PRAGMA foreign_keys = ON;

CREATE TABLE client (
	id	INTEGER NOT NULL PRIMARY KEY,
	connection_n	INTEGER NOT NULL DEFAULT 0,
	cumulative_time	INTEGER NOT NULL DEFAULT 0,
	connection_max_duration	INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE connection (
	id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	client	INTEGER NOT NULL,
	connected	INTEGER NOT NULL,
	disconnected	INTEGER NOT NULL,
	reason	INTEGER NOT NULL,
	ip	TEXT NOT NULL,
	server	INTEGER NOT NULL DEFAULT 0,
	duration INTEGER NOT NULL DEFAULT 0,
	log INTEGER NOT NULL,
	FOREIGN KEY(client) REFERENCES client(id),
	FOREIGN KEY(log) REFERENCES log(id)
);

CREATE TABLE nickname (
	client	INTEGER NOT NULL,
	nickname	TEXT NOT NULL,
	used	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(client, nickname),
	FOREIGN KEY(client) REFERENCES client(id)
);

CREATE TABLE merged (
	u1	INTEGER NOT NULL,
	u2	INTEGER NOT NULL,
	PRIMARY KEY(u1,u2),
	FOREIGN KEY(u1) REFERENCES client(id),
	FOREIGN KEY(u2) REFERENCES client(id)
);

CREATE TABLE log (
	id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name	TEXT NOT NULL UNIQUE,
	lines	INTEGER NOT NULL DEFAULT 0,
	size INTEGER NOT NULL DEFAULT 0
);
